name: CodeWork-Marketing-Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # (optional) clean out any stray folders that might confuse SWA
      - name: Cleanup old build folders
        run: |
          rm -rf .next .output api node_modules

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # your SWA deployment token
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_PLANT_0803BCA10 }}
          # GitHub token for comments, etc.
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload

          # ─── Your App Config ────────────────────────────────────────
          app_location: "/"                    # root of your Next.js project
          api_location: ""                     # <-- explicitly empty: no Azure Functions
          output_location: ".next/standalone"  # <-- point at your standalone build

          # ─── Build Commands ─────────────────────────────────────────
          app_build_command: "npm run build"  
          api_build_command: "echo No API to build"
