name: CodeWork-Marketing-Production

on:
  push:
    branches:
      - master
  workflow_dispatch: 

jobs:
  build_and_deploy_job:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_PLANT_0803BCA10 }}
          repo_token:                         ${{ secrets.GITHUB_TOKEN }}
          action:                             upload
          app_location:                       "/"     # your Next.js project root
          api_location:                       ""      # no Azure Functions
          output_location:                    "out"   # next export → out/
          app_build_command:                  "npm run build && npm run export"
          is_static_export:                   true
