name: CodeWork-Marketing-Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # (Optional) make sure nothing leftover gets picked up
      - name: Clean old build artifacts
        run: |
          rm -rf .next .output api node_modules swa-db-connections

      - name: Build & Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_PLANT_0803BCA10 }}
          repo_token:                              ${{ secrets.GITHUB_TOKEN }}
          action:                                 upload
          app_location:                           "/"                    # your Next.js root
          api_location:                           ""                     # ← explicitly empty!
          output_location:                        ".next/standalone"     # ← standalone build folder
          app_build_command:                      "npm run build"
          skip_api_build:                         true                   # ← skip any API packaging
